bin.includes = META-INF/,\
               .,\
               lib/cxf-core.jar,\
               lib/cxf-rt-bindings-soap.jar,\
               lib/cxf-rt-bindings-xml.jar,\
               lib/cxf-rt-databinding-jaxb.jar,\
               lib/cxf-rt-databinding-xmlbeans.jar,\
               lib/cxf-rt-frontend-jaxrs.jar,\
               lib/cxf-rt-frontend-jaxws.jar,\
               lib/cxf-rt-frontend-simple.jar,\
               lib/cxf-rt-rs-extension-providers.jar,\
               lib/cxf-rt-rs-service-description.jar,\
               lib/cxf-rt-security.jar,\
               lib/cxf-rt-transports-http.jar,\
               lib/cxf-rt-ws-addr.jar,\
               lib/cxf-rt-ws-policy.jar,\
               lib/cxf-rt-ws-transfer.jar,\
               lib/cxf-rt-wsdl.jar,\
               lib/neethi.jar,\
               lib/wsdl4j.jar,\
               lib/xmlschema-core.jar
